// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iulucnqcdztbquivripp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1bHVjbnFjZHp0YnF1aXZyaXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMDQ5NjgsImV4cCI6MjA3Mjc4MDk2OH0.sZWlvg53jwNP15IiUqcj0OLGSJMAg8BqrPiGv41Iu-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});